### PR TITLE
add staticcheck to ci

### PR DESCRIPTION
**Pull request by joshblum**

### CODE REVIEW

**Comment by patrickxb** [comment]
golangci-lint already runs staticcheck.

**Comment by patrickxb** [comment]
Enabled by your configuration linters:
staticcheck: Staticcheck is a go vet on steroids, applying a ton of static analysis checks [fast: false, auto-fix: false]
structcheck: Finds an unused struct fields [fast: true, auto-fix: false]
ineffassign: Detects when assignments to existing variables are not used [fast: true, auto-fix: false]
deadcode: Finds unused code [fast: true, auto-fix: false]
typecheck: Like the front-end of a Go compiler, parses and type-checks Go code [fast: true, auto-fix: false]
gofmt: Gofmt checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification [fast: true, auto-fix: true]
govet (vet, vetshadow): Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string [fast: true, auto-fix: false]
errcheck: Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases [fast: true, auto-fix: false]
unconvert: Remove unnecessary type conversions [fast: true, auto-fix: false]
varcheck: Finds unused global variables and constants [fast: true, auto-fix: false]
gocritic: The most opinionated Go source code linter [fast: true, auto-fix: false]
unused: Checks Go code for unused constants, variables, functions and types [fast: false, auto-fix: false]
gosimple: Linter for Go source code that specializes in simplifying a code [fast: false, auto-fix: false]

**Comment by patrickxb** [comment]
https://github.com/keybase/stellarnet/pull/58/files#diff-354f30a63fb0907d4ad57269548329e3R13

**Comment by joshblum** [comment]
oh even better.. maybe i should just use that wrapper, it uncovered some issues in the client

**Pull request closed without merging**
